### ISSUE TITLE
Issue with script Parrot OS

### ISSUE THREAD

**Issue by Gizmet** [mohinparamasivam/GitLab-11.4.7-Authenticated-Remote-Code-Execution#1]
[+] Retrieving CSRF token to submit the login form
Traceback (most recent call last):
  File "gitlab_rce.py", line 39, in <module>
    soup = BeautifulSoup(html_content,features="lxml")
  File "/usr/share/offsec-awae-wheels/beautifulsoup4-4.9.1-py2-none-any.whl/bs4/__init__.py", line 245, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

**Comment by mohinparamasivam** [comment]
install the parser library with 
pip install lxml

**Comment by Gizmet** [comment]
tried that and pip install bs4 no luck..

**Comment by Gizmet** [comment]
![image](https://user-images.githubusercontent.com/48859572/102678381-fc038400-4175-11eb-8484-a09d2339c370.png)

**Comment by mohinparamasivam** [comment]
lxml is installed under python3, install the python2 version

**Comment by Gizmet** [comment]
using pip2? doesnt work for me..any idea why?

**Comment by mohinparamasivam** [comment]
> using pip2? doesnt work for me..any idea why?

Can include a screenshot of running the script with the arguments followed by the error message?

**Comment by Gizmet** [comment]
![image](https://user-images.githubusercontent.com/48859572/102678649-ccee1200-4177-11eb-933a-c4e7a8025b12.png)

**Comment by mohinparamasivam** [comment]
https://stackabuse.com/introduction-to-the-python-lxml-library/

Try the apt-get method specified in this blog . If it doesn’t resolve try pip3 install lxml ... based on the screenshot the script is referring to python3 version of lxml idk y... on kali it works fine

**Comment by mohinparamasivam** [comment]
![Screenshot 2020-12-19 at 6 40 08 PM](https://user-images.githubusercontent.com/28557040/102687392-c029f680-4229-11eb-9b06-53f9687a29b0.png)

<b>Install lxml parser for python2.7 </b>
