### ISSUE TITLE
http server

### ISSUE THREAD

**Issue by ghost** [mohinparamasivam/GitLab-11.4.7-Authenticated-Remote-Code-Execution#11]
i have a problem with script and i cant find a solution, whats happened there
<img width="865" alt="Screen Shot 2022-08-23 at 21 24 10" src="https://user-images.githubusercontent.com/27805071/186251431-e299bede-6d41-4272-bc5a-8ef526ec1bdb.png">
n

**Comment by mohinparamasivam** [comment]
run with python not python3 , if incase u have to run with python3 I suggest you to replace the raw_input to input in the script.

**Comment by ghost** [comment]
this changing raw_input to input it works, version of python is not important. thanks for your help
