### ISSUE TITLE
ProxyError

### ISSUE THREAD

**Issue by br0scientist** [mohinparamasivam/GitLab-11.4.7-Authenticated-Remote-Code-Execution#3]
Hello, I am having the following issue and was wondering if anyone could help me remedy it:

![2020-12-22 16_31_29-Window](https://user-images.githubusercontent.com/61131669/102935077-64eb4480-4473-11eb-91f6-3d37ca0517af.png)

**Comment by TerryDev** [comment]
are you using burpsuite?

**Comment by mohinparamasivam** [comment]
> Hello, I am having the following issue and was wondering if anyone could help me remedy it:
> 
> ![2020-12-22 16_31_29-Window](https://user-images.githubusercontent.com/61131669/102935077-64eb4480-4473-11eb-91f6-3d37ca0517af.png)

@br0scientist Remove the proxy syntax in the code if ur not using any proxy through burpsuite..... to ease things up run ur burpsuit proxy on 127.0.0.1 port 8080 and run the script should work like charm 👍
