### ISSUE TITLE
HTTP SERVER ERROR

### ISSUE THREAD

**Issue by Calimtr7** [mohinparamasivam/GitLab-11.4.7-Authenticated-Remote-Code-Execution#4]
![image](https://user-images.githubusercontent.com/61936662/102942521-73812e00-446a-11eb-896b-eaff6b820141.png)
I got this when i run the option 1. Any solution?

**Comment by Calimtr7** [comment]
![image](https://user-images.githubusercontent.com/61936662/102942665-d2df3e00-446a-11eb-9003-1efb1d3206fe.png)

**Comment by Calimtr7** [comment]
and netcat doesn't work either

**Comment by mohinparamasivam** [comment]
@Calimtr7 Can u show me ur proxy settings in the script ?

**Comment by Calimtr7** [comment]
![image](https://user-images.githubusercontent.com/61936662/102994611-40738480-44d4-11eb-8379-57c476c300f8.png)

**Comment by Calimtr7** [comment]
this is my ip with openvpn

**Comment by Calimtr7** [comment]
Or i need to use BurpSuit?

**Comment by mohinparamasivam** [comment]
> Or i need to use BurpSuit?

disable the proxies=proxies in the request.post method and run the script if ur not using burpsuite... if ur using burpsuite then configure the proxy address accordingly
