### ISSUE TITLE
Incompatible script python2.7 ---> python3

### ISSUE THREAD

**Issue by HappyKharoud** [mohinparamasivam/GitLab-11.4.7-Authenticated-Remote-Code-Execution#6]
Can you please make it python3 compatible. I have fixed raw_input --> input but I don't know how to fix this error: 

Traceback (most recent call last):
  File "49263.py", line 223, in <module>
    payload=b"utf8=%E2%9C%93&authenticity_token={}&project%5Bimport_url%5D={}{}&project%5Bci_cd_only%5D=false&project%5Bname%5D={}&project%5Bnamespace_id%5D={}&project%5Bpath%5D={}&project%5Bdescription%5D=&project%5Bvisibility_level%5D=0".format(urlencoded_token_final,ipv6_url,reverse_shell,project_name,namespace_id,project_name)
AttributeError: 'bytes' object has no attribute 'format'

I searched online it says it's compatibility issue or tell me how to install RandomWords on python 2.7 because when I do pip install it installs for python3 by default.

**Comment by mohinparamasivam** [comment]
> Can you please make it python3 compatible. I have fixed raw_input --> input but I don't know how to fix this error:
> 
> Traceback (most recent call last):
> File "49263.py", line 223, in
> payload=b"utf8=%E2%9C%93&authenticity_token={}&project%5Bimport_url%5D={}{}&project%5Bci_cd_only%5D=false&project%5Bname%5D={}&project%5Bnamespace_id%5D={}&project%5Bpath%5D={}&project%5Bdescription%5D=&project%5Bvisibility_level%5D=0".format(urlencoded_token_final,ipv6_url,reverse_shell,project_name,namespace_id,project_name)
> AttributeError: 'bytes' object has no attribute 'format'
> 
> I searched online it says it's compatibility issue or tell me how to install RandomWords on python 2.7 because when I do pip install it installs for python3 by default.

pip install RandomWords==0.1.5

**Comment by mohinparamasivam** [comment]
> Can you please make it python3 compatible. I have fixed raw_input --> input but I don't know how to fix this error:
> 
> Traceback (most recent call last):
> File "49263.py", line 223, in
> payload=b"utf8=%E2%9C%93&authenticity_token={}&project%5Bimport_url%5D={}{}&project%5Bci_cd_only%5D=false&project%5Bname%5D={}&project%5Bnamespace_id%5D={}&project%5Bpath%5D={}&project%5Bdescription%5D=&project%5Bvisibility_level%5D=0".format(urlencoded_token_final,ipv6_url,reverse_shell,project_name,namespace_id,project_name)
> AttributeError: 'bytes' object has no attribute 'format'
> 
> I searched online it says it's compatibility issue or tell me how to install RandomWords on python 2.7 because when I do pip install it installs for python3 by default.

If you would like to port it to python3 it will be great... just remove the "b" in front of the request in python2 it sends as a binary data in python3 it doesn't require it... btw u need to change the imports if u wish to use python3
