### ISSUE TITLE
dependecy warnings

### ISSUE THREAD

**Issue by elliot-alderson1** [mohinparamasivam/GitLab-11.4.7-Authenticated-Remote-Code-Execution#7]
I installed all the dependencies, and i edited the target URL, and my command is right as shown in the vid but I'm still having this issue

```
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  from cryptography import x509
Traceback (most recent call last):
  File "gitlab_rce.py", line 4, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4
```

**Comment by mohinparamasivam** [comment]
> I installed all the dependencies, and i edited the target URL, and my command is right as shown in the vid but I'm still having this issue
> 
> ```
> /usr/local/lib/python2.7/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.10) or chardet (3.0.4) doesn't match a supported version!
>   RequestsDependencyWarning)
> /usr/local/lib/python2.7/dist-packages/OpenSSL/crypto.py:12: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
>   from cryptography import x509
> Traceback (most recent call last):
>   File "gitlab_rce.py", line 4, in <module>
>     from bs4 import BeautifulSoup
> ImportError: No module named bs4
> ```

seems like u didn't install the bs4 module 

pip install beautifulsoup4
or
pip install bs4
